# Generated by Django 3.1.5 on 2021-02-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_helper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cutomer_id',
            new_name='cutomer',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='helper_id',
            new_name='helper',
        ),
    ]
