# Generated by Django 3.1.5 on 2021-04-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_helper', '0002_auto_20210225_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='works',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Helper',
        ),
        migrations.DeleteModel(
            name='Works',
        ),
    ]
