# Generated by Django 3.1.5 on 2021-04-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='helper',
            name='name',
        ),
        migrations.RemoveField(
            model_name='helper',
            name='password',
        ),
    ]
